steps:
- id: 'Executando docker-compose'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk/docker/compose'
  args: ['-f', 'docker-compose.yaml', 'up', -d]

- id: 'Verificando se o container esta rodando'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['ps']

- id: 'Executando teste unitário'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['test']
  env: ['GOPATH=/go/src']


