steps:
- id: 'Executando docker-compose'
  name: 'docker/compose'
  args: ['-f', 'golang/docker-compose.yaml', 'up', -d]

- id: 'Verificando se o container esta rodando'
  name: 'gcr.io/cloud-builders/docker'
  #entrypoint: gcloud
  args: ['ps']

- id: 'Executando teste unitário'
  name: 'golang'
  entrypoint: go
  env: ['GOPATH=/go/src']
  args: ['test']
  volumes:
  - name: 'go'
    path: '/go/src'



