apiVersion: apps/v1
kind: Deployment
metadata:
    name: golang-deployment
    labels:
        app: golang
spec: 
    replicas: 1
    selector:
        matchLabels:
            app: golang
    template: #template do pod
        metadata:
            labels:
                app: golang
        spec: #especificacao do pod
            containers:
            - image: paulodutra/utilizando-k8s-golang:latest
              name: golang
              
              ports:
              - containerPort: 80
