apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-conf
data:
    nginx.conf : |
        server {
            listen 80;
            index index.html index.htm;
            root /usr/share/nginx/html;
        }
    html.conf : |
        Code.education Rocks.
    