apiVersion: apps/v1
kind: Deployment
metadata:
    name: desafio-nginx
    labels:
        app: desafio-nginx
spec:
    replicas: 3
    selector:
        matchLabels:
            app: desafio-nginx
    template: #template do pod 
        metadata:
            labels:
                app: desafio-nginx
        spec:
            containers:
            - name: desafio-nginx
              image: paulodutra/nginx-code-edu
              #command: ['/bin/sh', '-c', "cd /usr/share/nginx/html; rm index.html; touch index.html; echo '<h1>Code.education Rocks.</h1>' >> index.html; nginx start"]
              ports:
              - containerPort: 80
              volumeMounts: #monta o volume
              - mountPath: /etc/nginx/conf.d
                name: nginx-conf
                readOnly: true
            volumes:
            - name: nginx-conf
              configMap:
                name: nginx-conf
                items:
                    - key: nginx.conf
                      path: nginx.conf


            