apiVersion: v1
kind: Service
metadata:
    name: desafio-mysql-service
spec:
    ports:
        - port: 3306
    selector:
        app: desafio-mysql #igual esta no matchLabels do deployment.yaml
        tier: db
    clusterIP: None 